/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.form;

import Model.Model_HoaDon;
import Model.Model_SanPham;
import Model.Model_Vourcher;
import Repository.Repository_HDCT;
import Repository.Repository_HoaDon;
import Repository.Repository_Vourcher;
import Repository.reponsitory_SanPham;
import Repository.reponsitory_getImei;
import Repository.repository_KhachHang;
import form.Form_ThongTinKH;
import java.awt.Point;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import test.ImeiDialog;

/**
 *
 * @author macbook
 */
public class Form_BH extends javax.swing.JPanel {

    /**
     * Creates new form Form_SP
     */
    int count_hoaDonCho = 0;
    DefaultTableModel model;
    DefaultTableModel model_SPChitiet;
    DefaultTableModel model_HoaDon;
    DefaultTableModel model_GioHang;

    private reponsitory_SanPham rp = new reponsitory_SanPham();
    private reponsitory_getImei rpImei = new reponsitory_getImei();
    private Repository_HoaDon rpHD = new Repository_HoaDon();
    private Repository_HDCT rpHDCT = new Repository_HDCT();
    private repository_KhachHang rpKH = new repository_KhachHang();
    private Repository_Vourcher rpVoucher = new Repository_Vourcher();

    public Form_BH() {
        initComponents();
        fillToTable_ChiTiet(rp.gettAll_SpChiTiet());
        fillHoaDOnCho(rpHD.getAllChoHoaDonTT());
        CapNhatThoiGian();
        Timer timer = new Timer(1000, e -> CapNhatThoiGian());
        timer.start();

    }

    void CapNhatThoiGian() {

        LocalDateTime now = LocalDateTime.now();
        // Định dạng ngày
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String formattedDate = now.format(dateFormatter);

        // Đặt ngày vào JLabel
        lbl_Ngay.setText(formattedDate);

        // Lấy giờ hiện tại
        LocalTime now1 = LocalTime.now();
        // Định dạng giờ
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        String formattedTime = now1.format(timeFormatter);

        // Đặt giờ vào JLabel
        lbl_Gio.setText(formattedTime);

    }

    void fillToTable(ArrayList<Model_SanPham> ds) {
        model = (DefaultTableModel) tbl_DSSP.getModel();
        model.setRowCount(0);
        for (Model_SanPham d : ds) {
            model.addRow((Object[]) d.toDataSP());
        }
    }

    void fillToTable_ChiTiet(ArrayList<Model_SanPham> ds) {
        model_SPChitiet = (DefaultTableModel) tbl_DSSP.getModel();
        model_SPChitiet.setRowCount(0);
        for (Model_SanPham d : ds) {
            model_SPChitiet.addRow((Object[]) d.toData_CTSP());
        }
    }

    void fillCbo_Voucher_BH(ArrayList<String> ds) {
        cbo_MaGiamGia.removeAllItems();
        for (String d : ds) {
            cbo_MaGiamGia.addItem(d);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hoadon = new javax.swing.JTable();
        btn_HoaDon = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_XoaGioHang = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_GioHang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_DSSP = new javax.swing.JTable();
        btn_timkiemDSSP = new javax.swing.JButton();
        txt_timkiemDSSP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_MaKH = new javax.swing.JLabel();
        lbl_TenKH = new javax.swing.JLabel();
        txt_SDT_KH = new javax.swing.JTextField();
        btn_TimKiem_SDT = new javax.swing.JButton();
        btn_ThemMoiKH = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_LamMoi = new javax.swing.JButton();
        lbl_MaHD = new javax.swing.JLabel();
        txt_NgayThanhToan = new javax.swing.JTextField();
        lbl_maNhanVien = new javax.swing.JLabel();
        cbo_MaGiamGia = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        lbl_tienGiamGia = new javax.swing.JLabel();
        lbl_TongTien_sauKM = new javax.swing.JLabel();
        btn_ThanhToan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbl_TongTien = new javax.swing.JLabel();
        lbl_TongTien1 = new javax.swing.JLabel();
        lbl_Voucher_giamgiaCaoNhat = new javax.swing.JLabel();
        lbl_TongTien2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbl_MaNV = new javax.swing.JLabel();
        lbl_Gio = new javax.swing.JLabel();
        lbl_Ngay = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(963, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tbl_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã HD", "Ngày thanh toán", "Mã NV", "Tình trạng"
            }
        ));
        tbl_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_hoadon);

        btn_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-30.png"))); // NOI18N
        btn_HoaDon.setText("Tạo hóa đơn");
        btn_HoaDon.setToolTipText("");
        btn_HoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_HoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btn_HoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btn_XoaGioHang.setBackground(new java.awt.Color(102, 255, 255));
        btn_XoaGioHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_XoaGioHang.setText("Xóa");
        btn_XoaGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaGioHangActionPerformed(evt);
            }
        });

        tbl_GioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Đơn giá", "Số lượng", "Imei", "Thành tiền"
            }
        ));
        tbl_GioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_GioHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_GioHang);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_XoaGioHang))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_XoaGioHang)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tbl_DSSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Số lượng tồn kho", "Giá", "CPU", "GPU", "Ram", "Màu sắc", "Dung lượng"
            }
        ));
        tbl_DSSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DSSPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_DSSP);

        btn_timkiemDSSP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timkiemDSSP.setText("Tìm kiếm");
        btn_timkiemDSSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemDSSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_timkiemDSSP)
                        .addGap(45, 45, 45)
                        .addComponent(txt_timkiemDSSP, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_timkiemDSSP)
                    .addComponent(txt_timkiemDSSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên KH:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("SĐT:");

        btn_TimKiem_SDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/timkiemq1.png"))); // NOI18N
        btn_TimKiem_SDT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_TimKiem_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiem_SDTActionPerformed(evt);
            }
        });

        btn_ThemMoiKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemMoiKH.setText("+");
        btn_ThemMoiKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMoiKHMouseClicked(evt);
            }
        });
        btn_ThemMoiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemMoiKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_SDT_KH, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(lbl_MaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_TimKiem_SDT)
                    .addComponent(btn_ThemMoiKH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_MaKH))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl_TenKH)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_ThemMoiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_TimKiem_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_SDT_KH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã hóa đơn:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Mã NV:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Giảm giá:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Ngày thanh toán: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tổng tiền sau KM:");

        btn_LamMoi.setBackground(new java.awt.Color(102, 255, 255));
        btn_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LamMoi.setText("Làm mới");

        txt_NgayThanhToan.setEnabled(false);

        cbo_MaGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbo_MaGiamGiaMouseClicked(evt);
            }
        });
        cbo_MaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_MaGiamGiaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Tiền giảm giá: ");

        lbl_tienGiamGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tienGiamGia.setForeground(new java.awt.Color(255, 51, 51));

        lbl_TongTien_sauKM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_TongTien_sauKM.setForeground(new java.awt.Color(255, 51, 51));

        btn_ThanhToan.setBackground(new java.awt.Color(102, 255, 255));
        btn_ThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThanhToan.setText("Thanh Toán");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tổng tiền:");

        lbl_TongTien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbl_TongTien.setForeground(new java.awt.Color(255, 51, 51));

        lbl_TongTien1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbl_TongTien1.setForeground(new java.awt.Color(255, 51, 51));
        lbl_TongTien1.setText("VND");

        lbl_Voucher_giamgiaCaoNhat.setForeground(new java.awt.Color(255, 51, 0));

        lbl_TongTien2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbl_TongTien2.setForeground(new java.awt.Color(255, 51, 51));
        lbl_TongTien2.setText("VND");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_ThanhToan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_LamMoi)
                .addGap(41, 41, 41))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_NgayThanhToan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbo_MaGiamGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lbl_TongTien_sauKM, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_TongTien2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lbl_tienGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_TongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 23, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lbl_Voucher_giamgiaCaoNhat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_MaHD))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_maNhanVien))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_TongTien))
                .addGap(24, 24, 24)
                .addComponent(lbl_Voucher_giamgiaCaoNhat)
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_MaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbl_tienGiamGia)
                    .addComponent(lbl_TongTien1))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txt_NgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_TongTien_sauKM)
                    .addComponent(lbl_TongTien2))
                .addGap(82, 82, 82)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_LamMoi)
                    .addComponent(btn_ThanhToan))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(153, 204, 255));
        jPanel9.setForeground(new java.awt.Color(153, 204, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(1000, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N

        lbl_MaNV.setText("NV001");

        lbl_Gio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Gio.setText("19:01:02");

        lbl_Ngay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Ngay.setText("19:01:02");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_Gio)
                .addGap(26, 26, 26)
                .addComponent(lbl_Ngay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 680, Short.MAX_VALUE)
                .addComponent(lbl_MaNV)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(36, 36, 36))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_MaNV)
                        .addComponent(lbl_Gio)
                        .addComponent(lbl_Ngay))
                    .addComponent(jLabel15))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    void fillHoaDOnCho(ArrayList<Model_HoaDon> ds) {

        model_HoaDon = (DefaultTableModel) tbl_hoadon.getModel();
        model_HoaDon.setRowCount(0);
        for (Model_HoaDon d : ds) {
            model_HoaDon.addRow(d.toDataHoaDonCho());
        }

    }
    private void btn_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HoaDonActionPerformed
        // TODO add your handling code here:

        String maHd = lbl_MaNV.getText();
        String maNV = lbl_MaNV.getText();
        rpHD.getChoHoaDon(maHd, maNV);
        fillHoaDOnCho(rpHD.getAllChoHoaDonTT());
        lbl_maNhanVien.setText(lbl_MaNV.getText());
        int totalRows = tbl_hoadon.getRowCount();
        if (totalRows > 4) {
            JOptionPane.showMessageDialog(this, "Bạn đã tạo quá hóa đơn chờ cho phép!");
            btn_HoaDon.setEnabled(false);
        }

    }//GEN-LAST:event_btn_HoaDonActionPerformed

    private void btn_timkiemDSSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemDSSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timkiemDSSPActionPerformed

    public String getImei() {
        int i = tbl_DSSP.getSelectedRow();
        String getMaIemi = null;
        String maImei = tbl_DSSP.getValueAt(i, 0).toString();

        if (i != -1) {

            System.out.println("Mã sản phẩm được chọn: " + maImei); // Debug mã sản phẩm
            getMaIemi = openImeiDialog(maImei);
        }
        return getMaIemi;
    }

    private String openImeiDialog(String productId) {
        String maImei = null;
        System.out.println("Đang mở IMEI dialog cho sản phẩm: " + productId);
        ImeiDialog imeiDialog = new ImeiDialog(null, productId);

        imeiDialog.setVisible(true); // Hiển thị dialog
        maImei = imeiDialog.selectedImei;
        return maImei;
    }

    Model_SanPham readForm_GioHang(int i) {

        String maSp = tbl_DSSP.getValueAt(i, 0).toString();
        int soLuong = 1;
        double donGia = Double.parseDouble(tbl_DSSP.getValueAt(i, 2).toString());
        String Imei = getImei();
        if (Imei == null) {
            return null;
        } else {
            String maHD = lbl_MaHD.getText();
            Model_SanPham sp = new Model_SanPham(maSp, Imei, soLuong, donGia, maHD);
            return sp;
        }

    }

    void getAllGiohangtb(ArrayList<Model_SanPham> sp) {
        model_GioHang = (DefaultTableModel) tbl_GioHang.getModel();
        model_GioHang.setRowCount(0);
        double tongTien = 0;
        for (Model_SanPham model_SanPham : sp) {
            model_GioHang.addRow((Object[]) model_SanPham.toData_GioHang());
            tongTien += model_SanPham.getGia();
        }
        DecimalFormat df = new DecimalFormat("#,###.##"); // Hiển thị số có dấu phân cách hàng nghìn
        lbl_TongTien.setText(df.format(tongTien) + "");
    }
    private void tbl_DSSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DSSPMouseClicked
        // TODO add your handling code here:
        int i = tbl_DSSP.getSelectedRow();
            
            rpHDCT.ThemGioHang(readForm_GioHang(i));

            getAllGiohangtb(rpHDCT.getAllGioHangTamThoi(lbl_MaHD.getText()));
            //kiem tra voucher

            try {
                // Loại bỏ các ký tự phân cách như "," hoặc "."
                String tongTienStr = lbl_TongTien.getText().replace(",", "").replace(".", "");
                double tongTien = Double.parseDouble(tongTienStr);

                // Gọi phương thức fillCbo_Voucher_BH với giá trị tổng tiền
                fillCbo_Voucher_BH(rpVoucher.cboMaVoucher_FormBH(tongTien));

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        null,
                        "Lỗi định dạng số trong Tổng tiền: " + lbl_TongTien.getText(),
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE
                );
            
        }


    }//GEN-LAST:event_tbl_DSSPMouseClicked
    void getMaHoaDon() {
        int i = tbl_hoadon.getSelectedRow();
        String maHD = tbl_hoadon.getValueAt(i, 1).toString();
        lbl_MaHD.setText(maHD);
    }
    private void tbl_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hoadonMouseClicked
        // Lấy mã hóa đơn
        txt_NgayThanhToan.setText("");
        lbl_tienGiamGia.setText("");
        lbl_Voucher_giamgiaCaoNhat.setText("");
        getMaHoaDon();

        // Gọi phương thức để lấy thông tin khách hàng
        String[] thongTinKH = rpKH.getMaKh_TenKh(lbl_MaHD.getText());

        // Kiểm tra mảng trả về có phải null không
        if (thongTinKH != null && thongTinKH[0] != null) {
            lbl_MaKH.setText(thongTinKH[0]); // Mã khách hàng
            lbl_TenKH.setText(thongTinKH[1]); // Tên khách hàng
        } else {
            lbl_MaKH.setText(""); // Nếu không có thông tin, đặt trống
            lbl_TenKH.setText("");
        }

        // Hiển thị giỏ hàng tạm thời
        getAllGiohangtb(rpHDCT.getAllGioHangTamThoi(lbl_MaHD.getText()));

        // Kiểm tra và lấy Voucher
        getVoucher();

        int i = tbl_hoadon.getSelectedRow();
        String maNV = tbl_hoadon.getValueAt(i, 3).toString();
        lbl_maNhanVien.setText(maNV);
    }//GEN-LAST:event_tbl_hoadonMouseClicked
    //kiem tra lay voucher
    void getVoucher() {
        try {
            // Loại bỏ các ký tự phân cách như "," hoặc "."
            String tongTienStr = lbl_TongTien.getText().replace(",", "").replace(".", "");
            double tongTien = Double.parseDouble(tongTienStr);

            // Gọi phương thức fillCbo_Voucher_BH với giá trị tổng tiền
            fillCbo_Voucher_BH(rpVoucher.cboMaVoucher_FormBH(tongTien));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Lỗi định dạng số trong Tổng tiền: " + lbl_TongTien.getText(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }
    private void tbl_GioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_GioHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_GioHangMouseClicked

    String timKiemKH() {
        String sdt = txt_SDT_KH.getText();
        if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số điện thoại!");
            return null;
        }
        return sdt;
    }
    private void btn_TimKiem_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiem_SDTActionPerformed
        if (timKiemKH() != null) {
            if (!lbl_MaKH.getText().isEmpty()) {
                int i = JOptionPane.showConfirmDialog(null, "Bạn có muốn thay đổi thông tin không?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (i == 1) {
                    txt_SDT_KH.setText("");
                    return;
                }
            }

            // Gọi phương thức một lần và lưu kết quả
            String[] thongTinKH = rpKH.capNhatThongTinKH(txt_SDT_KH.getText(), lbl_MaHD.getText());

            if (thongTinKH != null) { // Kiểm tra nếu tìm thấy thông tin
                lbl_MaKH.setText(thongTinKH[0]); // Gán mã khách hàng
                lbl_TenKH.setText(thongTinKH[1]); // Gán tên khách hàng
            } else {
                JOptionPane.showMessageDialog(null, "Không tìm thấy thông tin khách hàng!");
            }

            // Xóa nội dung ô nhập
            txt_SDT_KH.setText("");
        }


    }//GEN-LAST:event_btn_TimKiem_SDTActionPerformed

    private void btn_ThemMoiKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMoiKHMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_ThemMoiKHMouseClicked

    private void btn_ThemMoiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemMoiKHActionPerformed
        // Kiểm tra nếu mã khách hàng không có giá trị (null hoặc rỗng)

        // Nếu mã khách hàng là null hoặc rỗng, hiển thị hộp thoại xác nhận
        int result = JOptionPane.showConfirmDialog(
                null,
                "Bạn có muốn thêm mới khách hàng không?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        if (result == JOptionPane.YES_OPTION) {
            // Lấy vị trí của nút bấm
            Form_ThongTinKH ttKh = new Form_ThongTinKH();
            Point btnLocation = btn_ThemMoiKH.getLocationOnScreen();

            int offsetX = 280; // Điều chỉnh mức độ lệch sang trái (50 pixel)
            ttKh.setLocation(btnLocation.x - offsetX, btnLocation.y + 50 + btn_ThemMoiKH.getHeight());

            // Hiển thị form
            ttKh.setVisible(true);
        }

    }//GEN-LAST:event_btn_ThemMoiKHActionPerformed

    private void cbo_MaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_MaGiamGiaActionPerformed
        // Kiểm tra xem combo box có dữ liệu hay không
        if (cbo_MaGiamGia.getItemCount() == 0) {

            return; // Dừng phương thức nếu combo box rỗng
        }

        // Nếu có dữ liệu, tiếp tục xử lý
        String tongTienStr = lbl_TongTien.getText().replace(",", "").replace(".", "");
        double tongTien = Double.parseDouble(tongTienStr);

        // Lấy mã voucher đã chọn
        String maVoucher = cbo_MaGiamGia.getSelectedItem().toString();

        // Kiểm tra nếu mã voucher không rỗng
        if (maVoucher == null || maVoucher.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một voucher.");
            return;
        }

        // Tính số tiền giảm giá
        double tienKM = rpVoucher.tinhTienGiamGia(tongTien, maVoucher);

        // Hiển thị số tiền giảm giá với định dạng
        DecimalFormat df = new DecimalFormat("#,###.##"); // Hiển thị số có dấu phân cách hàng nghìn
        lbl_tienGiamGia.setText(df.format(tienKM) + "");
        double tongTiensauKM = tongTien - tienKM;
        lbl_TongTien_sauKM.setText(df.format(tongTiensauKM));
        GetVoucherTotNhat();

    }//GEN-LAST:event_cbo_MaGiamGiaActionPerformed
    void GetVoucherTotNhat() {
        if (cbo_MaGiamGia.getItemCount() == 0) {

            return; // Dừng phương thức nếu combo box rỗng
        }
        String tongTienStr = lbl_TongTien.getText().replace(",", "").replace(".", "");
        double tongTien = Double.parseDouble(tongTienStr);

        String voucherTotNhat = rpVoucher.voucher_ToTNhat(tongTien);
        if (voucherTotNhat != null) {
            lbl_Voucher_giamgiaCaoNhat.setText("Voucher có mức Giảm giá cao nhất: " + voucherTotNhat);
        }
        String maVoucher = cbo_MaGiamGia.getSelectedItem().toString();
        double tienKM = rpVoucher.tinhTienGiamGia(tongTien, maVoucher);
        txt_NgayThanhToan.setText(lbl_Ngay.getText());

    }
    private void cbo_MaGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbo_MaGiamGiaMouseClicked
        if (cbo_MaGiamGia.getItemCount() == 0) {

            return;
        }
        String tongTienStr = lbl_TongTien.getText().replace(",", "").replace(".", "");
        double tongTien = Double.parseDouble(tongTienStr);

        String voucherTotNhat = rpVoucher.voucher_ToTNhat(tongTien);
        if (voucherTotNhat != null) {
            lbl_Voucher_giamgiaCaoNhat.setText("Voucher có mức Giảm giá cao nhất: " + voucherTotNhat);
        }
        String maVoucher = cbo_MaGiamGia.getSelectedItem().toString();
        double tienKM = rpVoucher.tinhTienGiamGia(tongTien, maVoucher);
        txt_NgayThanhToan.setText(lbl_Ngay.getText());


    }//GEN-LAST:event_cbo_MaGiamGiaMouseClicked
    void xoaTrang() {
        lbl_MaHD.setText("");

        lbl_TenKH.setText("");
        lbl_MaKH.setText("");
        lbl_TongTien.setText("");
        lbl_TongTien_sauKM.setText("");
        lbl_Voucher_giamgiaCaoNhat.setText("");
        lbl_maNhanVien.setText("");
        lbl_tienGiamGia.setText("");
        txt_NgayThanhToan.setText("");
        cbo_MaGiamGia.removeAllItems();
        model_GioHang.setRowCount(0);
    }

    Model_HoaDon capNhatlaiHoaDon() {
        // Lấy giá trị từ các JLabel và loại bỏ các ký tự không mong muốn
        String tongTienStr = lbl_TongTien.getText().replace(",", "").replace(".", "");
        String tongTienKMStr = lbl_tienGiamGia.getText().replace(",", "").replace(".", "");
        String tongTiensauKMStr = lbl_TongTien_sauKM.getText().replace(",", "").replace(".", "");
        String maVoucher = null;
        if (cbo_MaGiamGia.getItemCount() != 0) {
            maVoucher = cbo_MaGiamGia.getSelectedItem().toString();

        }

        // Chuyển đổi chuỗi thành số
        double tongTienDB = Double.parseDouble(tongTienStr);
        double tongKM = Double.parseDouble(tongTienKMStr);
        double tongTiensauKM = Double.parseDouble(tongTiensauKMStr);

        return new Model_HoaDon(maVoucher, tongTienDB, tongKM, tongTiensauKM);
    }

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        // TODO add your handling code here:
        int i = tbl_hoadon.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hóa đơn cần thanh toán!");
        }
        String maHD = tbl_hoadon.getValueAt(i, 1).toString();
        rpHDCT.getAllGioHangTamThoi(maHD);
        rpHDCT.ThemHDCT(rpHDCT.getAllGioHangTamThoi(maHD), maHD);

        JOptionPane.showConfirmDialog(null, "Bạn có muốn in hóa đơn không?");
        fillHoaDOnCho(rpHD.getAllChoHoaDonTT());
        ///Cap nhat hoa don vao bang hoa don
        rpHD.CapNhatHoaDonThanToan(capNhatlaiHoaDon(), maHD);
        //xoa trang

        xoaTrang();
        fillToTable_ChiTiet(rp.gettAll_SpChiTiet());
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void btn_XoaGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaGioHangActionPerformed
        // Kiểm tra người dùng đã chọn dòng nào trong bảng hay chưa
        int i = tbl_GioHang.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xóa!");
            return;
        }

        // Lấy giá trị mã IMEI từ dòng được chọn
        String maImei = tbl_GioHang.getValueAt(i, 4).toString();
        rpHDCT.XoaGioHang(maImei);

        // Cập nhật lại giao diện
        getAllGiohangtb(rpHDCT.getAllGioHangTamThoi(lbl_MaHD.getText()));
        getVoucher();
        GetVoucherTotNhat();
        if (cbo_MaGiamGia.getItemCount() == 0) {

            lbl_Voucher_giamgiaCaoNhat.setText("");
            lbl_tienGiamGia.setText("");
        }

    }//GEN-LAST:event_btn_XoaGioHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HoaDon;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JButton btn_ThemMoiKH;
    private javax.swing.JButton btn_TimKiem_SDT;
    private javax.swing.JButton btn_XoaGioHang;
    private javax.swing.JButton btn_timkiemDSSP;
    private javax.swing.JComboBox<String> cbo_MaGiamGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_Gio;
    private javax.swing.JLabel lbl_MaHD;
    private javax.swing.JLabel lbl_MaKH;
    private javax.swing.JLabel lbl_MaNV;
    private javax.swing.JLabel lbl_Ngay;
    private javax.swing.JLabel lbl_TenKH;
    private javax.swing.JLabel lbl_TongTien;
    private javax.swing.JLabel lbl_TongTien1;
    private javax.swing.JLabel lbl_TongTien2;
    private javax.swing.JLabel lbl_TongTien_sauKM;
    private javax.swing.JLabel lbl_Voucher_giamgiaCaoNhat;
    private javax.swing.JLabel lbl_maNhanVien;
    private javax.swing.JLabel lbl_tienGiamGia;
    private javax.swing.JTable tbl_DSSP;
    private javax.swing.JTable tbl_GioHang;
    private javax.swing.JTable tbl_hoadon;
    private javax.swing.JTextField txt_NgayThanhToan;
    private javax.swing.JTextField txt_SDT_KH;
    private javax.swing.JTextField txt_timkiemDSSP;
    // End of variables declaration//GEN-END:variables
}
